version: 0.0
os: linux

files:
  - source: ./
    destination: /home/centos

hooks:
  ApplcationStop:
    - location: ./applicationStop.sh
      timeout: 180

  AfterInstall:
    - location: ./afterInstall.sh
      timeout: 180

  ApplicationStart:
    - location: ./applicationStart.sh
      timeout: 180